# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns:
          - "*"
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: bitfield-struct
        versions: ['>=0.10.0']
    groups:
      cargo:
        patterns:
          - "*"
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: opengpio
        versions: ['>=2.0.0']
    groups:
      npm:
        patterns:
          - "*"
  # Apparently, dependabot fails to build this project's python binding.
  # It seems to use an env sequestered from the needed rust sources.
  # - package-ecosystem: uv
  #   directory: /
  #   schedule:
  #     interval: "weekly"
  #   groups:
  #     uv-pip:
  #       patterns:
  #         - "*"
