[workspace]
members = ["crates/*", "examples/rust", "bindings/*"]
default-members = ["crates/*", "bindings/*"]
resolver = "2"

[workspace.package]
repository = "https://github.com/nRF24/rf24-rs"
homepage = "https://nRF24.github.io/rf24-rs"
edition = "2021"
license = "MIT"

[workspace.dependencies]
linux-embedded-hal = { version = "0.5.0", default-features = false, features = ["gpio_cdev", "spi"] }
nix = "0.31.3"
bitfield-struct = "0.9.5"

[profile.release]
lto = true
strip = "symbols"
