site_name: rf24-rs
site_description: "The RF24 rust library"
site_url: "https://nRF24.github.io/rf24-rs"
repo_url: "https://github.com/nRF24/rf24-rs"
repo_name: "nRF24/rf24-rs"
edit_uri: "edit/main/docs/"
docs_dir: src
nav:
  - index.md
  - api-diff.md
  - changelog.md

theme:
  name: material
  features:
    - navigation.top
    - content.tabs.link
    - content.tooltips
    - content.code.annotate
    - content.code.copy
    - content.action.view
    - content.action.edit
    - navigation.footer
    - search.suggest
    - search.share
    - navigation.tracking
    - toc.follow
  logo: images/logo.jpg
  favicon: images/favicon.ico
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: yellow
      accent: cyan
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: yellow
      accent: cyan
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: yellow
      accent: cyan
      toggle:
        icon: material/lightbulb
        name: Switch to system preference
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nRF24/rf24-rs

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - include-markdown

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      linenums_style: pymdownx-inline
  # - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.snippets:
      check_paths: true
  - attr_list
  - admonition
  - markdown_gfm_admonition
