name: build and test CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - run: cargo build
      - run: cargo check
      - run: cargo fmt
      - run: cargo doc --no-deps
      - name: save docs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: rf24-rs docs
          path: target/doc
      - run: rustup component add llvm-tools-preview
      - name: Install cargo-nextest and cargo-llvm-cov
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-llvm-cov,cargo-binstall
      - name: Run tests
        run: cargo llvm-cov --lcov --output-path lcov.info
      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: lcov.info
          fail_ci_if_error: true
