# lint/build examples

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
          cache: "pip"
          cache-dependency-path: "examples/python/requirements*.txt"
      - name: Install workflow tools
        run: >-
          python -m pip install
          -r examples/python/requirements.txt
          -r examples/python/requirements-dev.txt
      - run: ruff check
      - run: ruff format
      - run: mypy

  build-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - run: rustup update --no-self-update
      - run: yarn install
      - name: Build binding (debug)
        run: yarn build:debug
      - name: Lint examples
        run: yarn examples-lint
      - name: Compile examples
        run: yarn examples-build

  lint-rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update --no-self-update
      - uses: cargo-bins/cargo-binstall@main
      - name: Install just
        run: cargo binstall -y just
      - run: just lint-examples