name: Rust

on:
  push:
    branches: [main]
    paths:
      - crates/**/*.rs
      - crates/**/Cargo.toml
      - .github/workflows/rust.yml
    tags:
      - 'rf24-rs/*'
      - 'rf24ble-rs/*'
      # - 'rf24network-rs/*'
      # - 'rf24mesh-rs/*'
  pull_request:
    branches: [main]
    paths:
      - crates/**/*.rs
      - crates/**/Cargo.toml
      - .github/workflows/rust.yml

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: Setup Rust
        run: rustup update --no-self-update
      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@ead08b90bd7b2e6d81963fb9cf0b7239f66d5db4 # v1.21.0
      - name: Install cargo-llvm-cov, cargo-nextest, and nur
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: cargo binstall -y cargo-nextest cargo-llvm-cov nur
      - name: Cache deps
        uses: actions/cache@v6.1.0 # zizmor: ignore[cache-poisoning]
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: cargo-crates-${{ hashFiles('crates/*/src/**', 'crates/**/Cargo.toml') }}
      - run: rustup component add llvm-tools-preview
        # this enables a tool (for default toolchain) needed to measure code coverage.
      - name: Run tests
        run: nur test --profile ci
      - name: Generate coverage reports
        run: nur test lcov
      - name: Upload coverage as artifact
        uses: actions/upload-artifact@v7
        with:
          path: lcov.info
          name: lcov.info

  coverage:
    needs: test
    runs-on: ubuntu-latest
    environment:
      name: test-coverage
      url: https://app.codecov.io/gh/nRF24/rf24-rs
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: Download coverage artifact
        uses: actions/download-artifact@v8
        with:
          name: lcov.info
      - uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        if: github.repository == 'nRF24/rf24-rs'
        id: codecov
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
          fail_ci_if_error: true

  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: startswith(github.ref, 'refs/tags/')
    permissions:
      # needed for trusted publishing
      id-token: write
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: Setup nushell
        uses: hustcer/setup-nu@ccd5bb5426b05a32009c2ba967946231f3919c97 # v3.25
        with:
          version: ${{ vars.NU_SHELL_VERSION || '*' }}
      - name: Get pkg from tag
        id: pkg
        shell: nu {0}
        run: |-
          let tag = $env.GITHUB_REF_NAME
          let pkg = $tag | parse "{name}/{version}" | first
          $"name=($pkg | get name)\n" | save --append $env.GITHUB_OUTPUT
      - name: Install Rust
        run: rustup update stable --no-self-update
      - name: Establish provenance
        uses: rust-lang/crates-io-auth-action@c6f97d42243bad5fab37ca0427f495c86d5b1a18 # v1.0.5
        id: auth
      - run: cargo publish -p ${PKG_NAME}
        env:
          PKG_NAME: ${{ steps.pkg.outputs.name }}
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
