name: Rust Release

permissions:
  contents: read

on:
  push:
    branches: [main]
    paths:
      - crates/**
      - '!crates/README.md'
      - Cargo.toml
      - Cargo.lock
    tags:
      - v*
  pull_request:
    branches: [main]
    paths:
      - crates/**
      - '!crates/README.md'
      - Cargo.toml
      - Cargo.lock

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

defaults:
  run:
    shell: bash

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install Rust
        run: rustup update stable --no-self-update
      - run: cargo publish -p rf24-rs
        if: startswith(github.ref, 'refs/tags')
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}